### ISSUE TITLE
Possible thread leak in GigaCounter

### ISSUE THREAD

**Issue by tobiasbaum** [SLP-team/SLP-Core#11]
While repeatedly analyzing a large codebase, I (probably) ran out of native threads. Looking at the source of GigaCounter, it seems like every counter creates its own ForkJoinPool, which is never shut down. I guess this leads to a thread leak.

I'm using v0.3 as published on GitHub.

Here's the stacktrace:
```
[443193,061s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
Exception in thread "main" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.base/java.lang.Thread.start0(Native Method)
        at java.base/java.lang.Thread.start(Thread.java:813)
        at java.base/java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1318)
        at java.base/java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1341)
        at java.base/java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1467)
        at java.base/java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:1937)
        at java.base/java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:1958)
        at java.base/java.util.concurrent.ForkJoinPool.submit(ForkJoinPool.java:2531)
        at slp.core.counting.giga.GigaCounter.submitTask(GigaCounter.java:147)
        at slp.core.counting.giga.GigaCounter.countBatch(GigaCounter.java:119)
        at slp.core.modeling.ngram.NGramModel.learn(NGramModel.java:49)
        at slp.core.modeling.runners.ModelRunner.learnTokens(ModelRunner.java:132)
        at slp.core.modeling.runners.ModelRunner.lambda$0(ModelRunner.java:106)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at slp.core.modeling.runners.ModelRunner.learnDirectory(ModelRunner.java:104)
        at de.unihannover.reviews.extractSlpCodebaseFeatures.ExtractSlpCodebaseFeatures.buildModel(ExtractSlpCodebaseFeatures.java:115)
        at de.unihannover.reviews.extractSlpCodebaseFeatures.ExtractSlpCodebaseFeatures.analyzeTicket(ExtractSlpCodebaseFeatures.java:92)
        at de.unihannover.reviews.extractSlpCodebaseFeatures.ExtractSlpCodebaseFeatures.main(ExtractSlpCodebaseFeatures.java:68)
j
```

My Java version is Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
And "cat /proc/sys/kernel/threads-max" says 256316

The error occured after the program had run for 5 days, so I didn't try to replicate so far.

**Comment by VHellendoorn** [comment]
Hi, thanks for notifying me. Sorry for the lost time there. Each GigaCounter instance caps its ForkJoinPool at 1,000 threads at present. If you could provide a bit more information:
- Are you counting across many GigaCounters?
- Are you running multiple instances of SLP-Core?
- Approximately how large is/are the corpus/corpora you are counting? (feel free to omit this if it's sensitive)

As a quick fix, reducing the max live thread count on line 146 may resolve this, but I'd like to get a feel for the kind of usage that leads to such crashes. It might be better if the codebase uses a single shared FJP.

**Comment by tobiasbaum** [comment]
I perform an analysis for (almost) every commit of a repository, one after the other all in the same Java process (i.e. checkout+analyze in a loop, no parallelism on my side). Regarding the size of the codebase, SLP said for the last checkout before the error "Counting complete: 12063372 tokens processed in 13s". It's several hundred-thousand lines of Java code. The error occurred after analyzing roughly 12000 commits.

There is one model for the whole codebase and nested models for subdirectories etc (similar to your NestedModel, but I couldn't use it directly in my case due to some difficulties). The latter ones are instantiated using reflection and the default constructor, so if I did not miss anything they should be using MapTrieCounter and not GigaCounter, i.e. there is one GigaCounter per checkout. The analysis code is not particularly sensitive, so I could provide it if you need it. I cannot provide the analyzed codebase.

BTW: Thanks for making your library available. And if you're interested in the larger context: I'm using it to create some features for prediction of code review remarks.

**Comment by mpatsis** [comment]
The OutOfMemoryError could be due to not having enough heap space in your JVM.
Have you checked what your default maximum heap space size is?
You can set this -Xmx option.

**Comment by tobiasbaum** [comment]
The max heap size of Java was 8 GiB (the whole machine has 32). This, and the text of the error message, make me suspect that it's probably an issue with the max number of threads resource limit and not the usual Xmx issue.

**Comment by VHellendoorn** [comment]
Thanks for the follow-up. This is apparently not implausible with ForkJoinPool; it can allocate [far more active threads than running threads](https://stackoverflow.com/questions/16789288/java-lang-outofmemoryerror-unable-to-create-new-native-thread) (the latter is limited by the parallelism, which is typically just about 4).

There are two fixes I am envisioning: sharing a single static ForkJoinPool across GigaCounter instances, since the number of cores is anyways limited, and explicitly limiting the maxPoolSize in GigaCounter even farther. If this doesn't work, I will also look into FixedThreadPools. I'm currently not at my usual work computer, so will work on this tonight (my time) and push a new release if it works.

**Comment by VHellendoorn** [comment]
The latest commit on master has the above-mentioned fix. I'm almost certain this addresses the problem, as it caps the total threads across all `GigaCounter`s to 100, but can't guarantee it at present. I will push a release with a more complete revision when I have time to test this more properly; in the meantime I hope the patch I pushed will help. Let me know if you need a Jar of it too.

**Comment by tobiasbaum** [comment]
Thanks for the fix. I just had a look at  b6284272f02b406f73f7b709cc5bbaa727492f83 and agree that it will probably fix the problem. The maven build ran successfully, so you don't need to provide a preliminary Jar. I'll give it a try shortly.

**Comment by tobiasbaum** [comment]
FYI: The fixed version successfully ran to completion.

**Comment by VHellendoorn** [comment]
Great to hear, thanks so much for testing it. I'll close this issue then.

**Comment by VHellendoorn** [comment]
Hi, just want to notify you that I inadvertently pushed buggy code in the cache model in the commit preceding the above bug-fix. Should you have used that model, please note that its performance may have been unfairly inflated if you used it for self-testing (any kind of test in which you remove a file, model it with cache, and re-add it afterwards). The fix hash now been pushed to master. Sorry for the inconvenience.
